### PR TITLE
Minor fix for macro atom pop solver

### PR DESCRIPTION
**Pull request by ssim**
Possible solution to current issue on #425

### CODE REVIEW

**Comment by jhmatthews** [comment]
Hmm. Curiouser and curiouser. So this fix appears to have introduced an error into the c34.pf model that wasn't there before. That's a bit of a mystery to me...I'm on my way to visit @ssim so we will have a chat about this.

**Comment by jhmatthews** [comment]
@kslong - fix made Knox, sorry for delay, we now catch the situation that ion density is zero. Could you try the test run out?

**Comment by kslong** [comment]
I’ve begun the tests.  I will let you know how they turn out.

**Comment by kslong** [comment]
Sigh @jhmatthews  ... this time fiducial_agn_c34 ran to completion but fiducial_agn_c345 did not (with mpirun -np 8).  It failed during Cycle 13 in thread 4 with this error.

Error: matom: macro atom level has no way out 11 0 0

There were no log/error statements before this error to indicate why it failed.  It was midway through transferring photons through the wind.

**Comment by jhmatthews** [comment]
Thanks Knox - I think this is the problem I was seeing before I got ran into the restart issue (and I wasn't sure if it was to do with reading in the atomic atomic data). It means that somehow a macro-atom is being activated into it's true ground state i.e. energy = 0, bottom state of CIII, which should never happen because an activated state should always be the upper level. The question is then how it manages to get into this level in the first place.

Since all jumping probabilities are proportional to lower level energy (see Lucy or Stuart's talk from Belfast), once it gets to this incorrect activated state it will produce the above error.

**Comment by jhmatthews** [comment]
Any ideas how that could happen @ssim ?

**Comment by jhmatthews** [comment]
I think this pull request should be merged in any case, and discussion can continue on #425 - agree @kslong ?

**Pull request merged**
