### PR TITLE
Fix for reposition bug

### PR DESCRIPTION
**Pull request by saultyevil**
This is the proposed fix for issue #584. Essentially, it treats the photons which are pushed into the disk by dfudge as a special case and deals with them by moving them a more _appropriate_ distance from the last resonance interaction. In principle, it could potentially be extended to help treat photons lost to dfudge as well. Results from the regression test suite look positive as do tests with my TDE models.

I also made a slight change to Exit to flush the logfile as sometimes it was not fully up to date on exiting.

### CODE REVIEW

**Comment by kslong** [comment]
Does this work if the disk is NOT flat?

**Comment by saultyevil** [comment]
Ah, that completely slipped my mind. I'll test some vertically extended discs before I move any further.

**Comment by saultyevil** [comment]
As far as I can tell, the fix I have implemented does not effect geometrically thick discs. It's pretty much coded so it only affects the DISK_FLAT checks in `walls ()`.

In the discs I did try there are photons which seem to become "stuck" in the disc between two translates as the error "walls: %d The previous position %11.4e %11.4e %11.4e was inside the disk, correcting by  %11.4e" is printed. These photons have not undergone a resonant scatter and so aren't being pushed into the disc by `reposition ()` so don't seem related to the original issue this fix is dealing with.

**Comment by kslong** [comment]
That was sort of what I was worried about because I did see that things were specifically set up for a flat disk.  While I expect your fixes have “done no harm”, I just wanted to make sure that a similar problem did appear with a thick disk.  Running the same tde model that generated the original problem, but using a thick disk should tell us.

**Comment by saultyevil** [comment]
I have double checked the same TDE model again and with a standard cv model, both with various parameter choices for the vertically extended disk. I have not seen any evidence of a photon passing through the disk plane like in the flat disk case due to reposition (), but at least in the TDE model something potentially curious is going on either way - long story short is that ds_to_disk is sometimes returning large values for shallow angles... But, this is something we can discuss in the telecon and decide if this is an issue or not.

**Pull request merged**
