### PR TITLE
Add variable to control number of wavelength bins

### PR DESCRIPTION
**Pull request by saultyevil**
After some procrastination from writing, these are the proposed changes in Issue #747 which wanted a parameter to specify the number of wavelength bins for the spectra.

A new parameter has been added "Spectrum.nwave" which controls how many wavelength bins there are for the ionization and spectral cycle spectra. I opted for specifying the number of bins rather than delta lambda as I think this is less error prone, i.e. you may specify a delta lambda of 0.25 over a huge wavelength range by mistake and end up with a massive number of bins creating a huge spectrum file. There is minimum number of wavelength bins of 25 (defined by NWAVEMIN) but I haven't added a maximum cap.

I have updated all of the example parameter files, other than regress.old, with Spectrum.nwave 10,000 as this was the value of NWAVE prior to this change. I've also added a python script to py_progs whose purpose is to update parameter names/values--pretty similar to add_param.py.

Since these changes modified xxspec and require dynamic allocation of the spectrum arrays (and the removal of an unused array), backwards computability has, once again, unfortunately been broken. I have labelled this version as py85c and Python will exit if it does not see a certain header in the .spec_save files. 

Restarting models have been fine for me, and I've tested it on three machines to make sure it wasn't a fluke. Just be sure to do a full clean of old object files before trying to run with the new version.

The regression tests seem to indicate I didn't break anything. The difference spectra for the regression tests do look a bit odd (see plot below), I guess because the binning might be slightly different now for some reason--but the difference is (rather) small anyway. I can't see a difference in the actual overplotted spectra.

agn_macro

cv

### CODE REVIEW

**Comment by jhmatthews** [comment]
Should this be merged @saultyevil ?

**Comment by jhmatthews** [comment]
I've resolved conflicting version number using web editor (which is a nice new feature).

**Comment by saultyevil** [comment]
Sorry, not just yet... after feedback from some telecon, I need to make a couple of changes to the "internal" spectra for the ionization cycles etc. Knox pointed out that it would probably be preferable for them to have a (large?) fixed value (10,000 or so) and so only the .spec spectra should be controlled by the new variable. I haven't gotten around to doing it just yet because of writing the paper etc, but it's top of my list when that's done!

**Comment by saultyevil** [comment]
Huh, the Balmer test seems to be sensitive to Python version number according to the last travis build...

**Comment by saultyevil** [comment]
I've fixed the number of bins for the ionization cycles to NWAVE_IONIZ = 10,000, as it was before. Of course, we could turn up this value as well as I believe someone thought this was closer to 40, 000.

With the current implementation, since it is dynamically allocated, you can specify nwave for the spectral cycles to be pretty much anything, but it can't be smaller than 10. I thought this would be better than forcing an upper limit of NWAVE_IONIZ. Doing this wouldn't guarantee backwards compatibility with older python version, since an extra variable will be required in the wind_save/spec_save to track the number of spectral cycle bins (and changing NWAVE_IONIZ, to get more bins, for a one time run will break that backwards compatibility of the spec_save anyway). I'm probably solving a problem which may not exist, but you never know :)

For the sake of code simplicity with communication between MPI processes, I opted to creating all arrays with the largest number of bins value so if the nwave for the spectrum cycles is too large, it'll also crash in the ionization cycles. This probably avoids some heart-ache, but isn't as memory efficient as it could be -- though it is not a limiting factor in terms of overall memory usage.

Below are some plots from the regression tests -- ignore the date, I haven't made changes to the code since 23 March and I'm 
only just getting around to looking at this PR again. There are _small_ differences according to the flux difference plots, but it's very hard to see the differences in the actual spectra. The differences come from _slight_ differences in binning, as I cleaned up some variables which were recalculated over and over, i.e. dlamba, instead of using pre-calculated values.

I'll be merging in tomorrow afternoon if there are no complaints.

cv_kur
agn_macro_gamma

**Pull request merged**
