### PR TITLE
Implementing a colour correction

### PR DESCRIPTION
**Pull request by jhmatthews**
This is a first implementation of the colour correction for discs in python (see #1008). The Colour correction can be used through the following options:

```
Disk.rad_type_to_make_wind(bb,models,fcol) fcol
Disk.rad_type_in_final_spectrum(bb,models,uniform,mono,fcol) fcol
```

If you select fcol in the first one, then another question will be asked: 

```
Disk.colour_correction(done) done
```

for which the only current option is "done".

### CODE REVIEW

**Comment by jhmatthews** [comment]
Can I merge this @kslong ?

**Comment by kslong** [comment]
@jhmatthews  yes, I think you can merge it, though I think the name fcol is not very user friendly, as what one means is a modified bb, in that since bb_fcol, as you described in the issue might have been clearer, or even color_corrected_bb.  

We have used more descriptive terms in other places, and I would prefer that.  As it's a minimum match one does not have to type everything.  Of course, for this reason one would want to check that using bb_corrected, or something would not mess up simple bb models.  Maybe mod_bb.  "done' is equally confusing, I would put Done in the command, though in fact, I think we do a lower case transition.  ...

OK here is what I would suggests

````
Disk.rad_type_to_make_wind(bb, mod_bb, models) mod_bb
Disk.rad_type_in_final_spectrum(bb, mod_bb, models,uniform,mono) mod_bb

Disk.bb_prescription(Done) Done
````

with the latter suggestion in part to avoid confusion between color and colour.

**Comment by jhmatthews** [comment]
Will make done capitalised. I could call it Done2012 or something to make it more explicit. 

mod_bb I'm less in favour of since this does explicitly set a colour correction at the moment and modified BB has all sorts of meanings - f or fcol is the general notation used in the literature. I don't make making it more explicit though.

**Comment by jhmatthews** [comment]
I do think also there's an argument for brevity in the parameter file(i.e. colour_corrected_bb would be too long) particularly if we are likely to add more options and keep the (options,) format for the keywords. 

For documenting the parameter options, can I just manually update the readthedocs page?

**Comment by kslong** [comment]
I liked mod_bb = modified_bb; I think fcol is an "inside" term for the AGN community, especially as you are planning additional versions of Done, or Done12.  I am not too bothered by longish names, as the switch from numbers to names was intended to make things more self evident.  But you should decide, make whatever changes you want, and go ahead and merge.

**Comment by jhmatthews** [comment]
I've now modified the syntax/keywords as Knox suggests, so this can be merged once we've sorted the unit tests.

**Comment by jhmatthews** [comment]
Merging this as tests now pass with reverted change in dev. Docs probably need improving a bit but I'm struggling to build them locally at the moment

**Pull request merged**
