### PR TITLE
Reorganisation of python.c and some inputs

### PR DESCRIPTION
**Pull request by jhmatthews**
This is a proposed reorganisation of python.c - any thoughts welcome. It should be tested and can be improved.

Most parameter file functionality would remain the same but disk.type has been moved below system type (see #8 and #44). The parameter files in examples are updated, and you can run my new py_progs/pf_update2.py script to update files once you've done one of them manually.

### CODE REVIEW

**Comment by jhmatthews** [comment]
@smangham @kslong @Higginbottom are people OK if I merge this? It passed the travis readin tests that I wrote for a variety of models, and I was pretty careful. Note that it will require reordering of parameter files. This can be done by updating one of the files to the correct order then running 

```
ls *.pf > files_to_update
pf_update2.py [-c -o] new.pf files_to_update
```

see py_progs/pf_update2.py docstring for usage. It's possible you could get some conflicts if you've been working on e.g. python.c

Also, related- I've created a branch called release. This will **always** contain the latest, hopefully well-tested actual release version of python.

**Comment by Higginbottom** [comment]
It all sounds cool to me!

**Comment by kslong** [comment]
I agree we should go ahead with this

**Comment by jhmatthews** [comment]
Cool. merging. Closes #8 closes #44 and partially addresses #136

**Comment by kslong** [comment]
setup.c has a lot of uninitialized variables.   We should fix this.

**Comment by jhmatthews** [comment]
Hmm, @kslong  I'm not getting these on either my mac (with both gcc 4.2, clang 4.1) or on iridis with gcc 4.4.6. Do you have an example warning message?

**Comment by kslong** [comment]
Here is what I see

setup.c:1130:12: warning: variable 'opar_stat' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1187:11: note: uninitialized use occurs here
  return (opar_stat);
          ^~~~~~~~~
setup.c:1130:8: note: remove the 'if' if its condition is always false
  else if (strncmp (files.root, "stdin", 5) == 0
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1130:12: warning: variable 'opar_stat' is used uninitialized whenever '||' condition is true [-Wsometimes-uninitialized]
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1187:11: note: uninitialized use occurs here
  return (opar_stat);
          ^~~~~~~~~
setup.c:1130:12: note: remove the '||' if its condition is always false
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1130:12: warning: variable 'opar_stat' is used uninitialized whenever '||' condition is true [-Wsometimes-uninitialized]
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1187:11: note: uninitialized use occurs here
  return (opar_stat);
          ^~~~~~~~~
setup.c:1130:12: note: remove the '||' if its condition is always false
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1130:12: warning: variable 'opar_stat' is used uninitialized whenever '||' condition is true [-Wsometimes-uninitialized]
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1187:11: note: uninitialized use occurs here
  return (opar_stat);
          ^~~~~~~~~
setup.c:1130:12: note: remove the '||' if its condition is always false
  else if (strncmp (files.root, "stdin", 5) == 0
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1124:7: warning: variable 'opar_stat' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if (strncmp (files.root, "dummy", 5) == 0)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1187:11: note: uninitialized use occurs here
  return (opar_stat);
          ^~~~~~~~~
setup.c:1124:3: note: remove the 'if' if its condition is always false
  if (strncmp (files.root, "dummy", 5) == 0)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setup.c:1122:16: note: initialize the variable 'opar_stat' to silence this warning
  int opar_stat;
               ^
                = 0
5 warnings generated.

On

Sakana: source $ clang -v
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Comment by jhmatthews** [comment]
Thanks Knox. your compiler seems better than mine. Will fix that

**Comment by kslong** [comment]
Just different, probably, not better.  But it is good to see what warnings are thrown by various compilers.  Knox

**Comment by jhmatthews** [comment]
I likle that it actually goes through some of the code logic too. Anyway- this should be fixed by commit https://github.com/agnwinds/python/commit/a608bb66982fe4b6a513671edae368df10a6acb6 to dev

**Pull request merged**
