### PR TITLE
Importing electron and radiation temperatures

### PR DESCRIPTION
**Pull request by saultyevil**
This PR is to fix issue #667. Both T_r and T_e can now be set with an imported grid. The behaviour of the how models are read in can be found in docs/sphinx/source/import.rst, I think I've detailed the majority of the information required to create a model to import. 

To quickly give an example of how reading the temperatures work now, for a spherical model we require the following columns,

i, r, v_r, rho

Optionally you can also provide the electron and radiation temperature, with the following behaviour,

* If no temperature is provided, T_e and T_r as set as Wind.t.init
* If T_e is provided, this value is set in plasmamain and T_r is set as T_r = 1.1 T_e
* If T_e and T_r are both provided, then plasmamain uses the values of T_e and T_r which were read in

In other news I've also "revamped" the routines in general. I've improved the documentation where I thought things weren't as clear, added in some safety nets (i.e. adding a catch to stop reading in when ncell > NDIM_MAX), and switched to dynamic memory allocation for the imported models structures (to be more memory efficient). I've unfortunately touched more files than I've actually modified, this has been due to fixing spelling mistakes whilst debugging and indent touching lines in other files.

### CODE REVIEW

**Comment by saultyevil** [comment]
Does Travis still work for PRs?

**Comment by kslong** [comment]
This looks great to me.  From my perspective, we should go ahead an squash and merge into dev.

I am not worried about the multiple domain issue, if it still exists, but it would be sensible to have Python throw and error if some tries to do this, and then exit

**Comment by saultyevil** [comment]
I've fixed the multiple domains issue and tested by importing two cv_standard winds with different temperatures. In py_wind, each domain had a different temperature.

**Comment by jhmatthews** [comment]
Weird, @saultyevil - indeed it seems travis isn't building PRs anymore. Seems it stopped a few PRs back, but I've no idea why.

**Comment by kslong** [comment]
What are PRs and what does this mean for us?

Sent from my iPad

On Mar 3, 2020, at 10:59 AM, James Matthews <notifications@github.com> wrote:

﻿

Weird, @saultyevil<https://github.com/saultyevil> - indeed it seems travis isn't building PRs anymore. Seems it stopped a few PRs back, but I've no idea why.

**Comment by saultyevil** [comment]
PRs = Pull requests.

It looks like Travis hasn't run for the latest commit in dev either..

**Pull request merged**
