### PR TITLE
Reverberation Mapping Commits

### PR DESCRIPTION
**Pull request by smangham**
Stripped back version of reverberation mapping commits. Keplerian disk code trimmed, all files reverted to old indent and prototype mode (bar trans_phot).

Code for reverberation mapping. The post processing code used to build transfer function maps from the .delay_dump files is at:
https://github.com/smangham/bindata

The following option(s) are added to input files after "Use.standard.care.factors(1=yes)":
reverb.type(0=no,1=phot,2=wind) 2
reverb.path_bins 30 - If type 2, sets number of path bins discretised 
reverb.theta_bins 30 - If type 2, used for output of .vtk file

### CODE REVIEW

**Comment by jhmatthews** [comment]
This looks good, much easier to see changes. Still failing build at the mo

**Comment by smangham** [comment]
Yeah, more py_wind issues- this should deal with it. I tested python compile locally but not py_wind, which was a mistake.

**Comment by jhmatthews** [comment]
I do it all the time

**Comment by smangham** [comment]
The test input file's missing the new lines required for reverb settings (reverb.type = 0/1, or reverb.type = 2 and reverb.path_bins and reverb.theta_bins) so Travis is stalling- is it possible to edit them in?

**Comment by jhmatthews** [comment]
sorry sam missed this - Yep just edit all the pf files in examples/

**Comment by jhmatthews** [comment]
Woops @smangham we forgot about this. It looks good to merge, what do you say?

**Comment by smangham** [comment]
Yeah, everything's in place and there's no more tweaks needed.

**Comment by jhmatthews** [comment]
Merging this. @Higginbottom @kslong please note you will have to update your parameter files to run with this version of the code. This can be done by creating a template.pf file with the same format as the files you want to update + the line 

```
reverb.type(0=no,1=phot,2=wind)    0
```

then running

```
ls *.pf > list.ls
pf_update2.py -o template.pf list.ls
```

see Python/py_progs/html_docs/pf_update2.html for docs.

**Pull request merged**
